# Generated by Django 5.1 on 2025-08-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fundraiser',
            new_name='Campaign',
        ),
    ]
