# Generated by Django 5.1 on 2025-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_fundraiser_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
