# Generated by Django 5.1 on 2025-08-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_campaign_owner_id_campaign_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='alt_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='alt_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='alt_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Stretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stretches', to='campaigns.campaign')),
            ],
        ),
    ]
